appname = opendata
httpport = 14001
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = opendata
redisEndpoint =
isDemoMode = false
logConfig = {"adapter":"file", "filename": "logs/opendata.log", "maxdays":99999, "perm":"0770"}
staticBaseUrl = ""
htmlTitle = "OpenData"
storageProvider = "local"
storagePath = "./files"
