appname = opendata
httpport = 13000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = mysql
dataSourceName = root:123456@tcp(localhost:3306)/
dbName = opendata
redisEndpoint =
isDemoMode = false

casdoorEndpoint =
clientId =
clientSecret =
casdoorOrganization =
casdoorApplication =
redirectPath = /callback

socks5Proxy =
staticBaseUrl = "https://cdn.casbin.org"
frontendBaseDir = "../opendata"
logConfig = {"adapter":"file", "filename": "logs/opendata.log", "maxdays":99999, "perm":"0770"}
